import type { MenuItemLocalePatch } from "./menuPatchTypes";

/** Korejské překlady položek menu (stejná struktura jako EN). */
export const MENU_ITEM_KO: Record<string, MenuItemLocalePatch> = {
  "polevka-rajcatova": {
    name: "토마토 수프",
    description: "바질, 파마산.",
    portionNote: "약 300 ml (250–340 ml, ± 10 %)",
    ingredients: [{ name: "토마토" }, { name: "바질" }, { name: "파마산 치즈" }],
    addons: {
      "polevka-rajcatova-parmazan": { label: "파마산 추가", portionNote: "15 g" },
      "polevka-rajcatova-pečivo": { label: "바삭한 빵", portionNote: "40 g" },
      "polevka-rajcatova-chilli": { label: "고추 추가", portionNote: "5 g" },
      "polevka-rajcatova-smetana": { label: "휘핑크림/생크림 추가", portionNote: "30 ml" },
    },
  },
  "polevka-kureci": {
    name: "닭 육수 수프",
    description: "국수, 뿌리 채소.",
    portionNote: "약 320 ml (± 10 %)",
    ingredients: [
      { name: "닭 육수" },
      { name: "국수" },
      { name: "당근" },
      { name: "셀러리" },
      { name: "파슬리" },
    ],
    addons: {
      "polevka-kureci-bezlepkove-nudle": { label: "글루텐 프리 국수", portionNote: "일반 대신 50 g" },
      "polevka-kureci-nudle": { label: "국수 추가", portionNote: "50 g" },
      "polevka-kureci-maso": { label: "육수 고기 추가", portionNote: "40 g" },
      "polevka-kureci-bylinky": { label: "신선 허브 추가", portionNote: "5 g" },
      "polevka-kureci-vejce": { label: "수프에 스크램블 에그", portionNote: "1개" },
    },
  },
  "polevka-cesnecka": {
    name: "마늘 수프",
    description: "치즈 토스트, 크루통.",
    portionNote: "약 330 ml (± 10 %)",
    ingredients: [{ name: "마늘" }, { name: "감자" }, { name: "크루통" }, { name: "치즈" }],
    addons: {
      "polevka-cesnecka-syr": { label: "그라탕용 치즈 추가", portionNote: "30 g" },
      "polevka-cesnecka-krutony": { label: "크루통 추가", portionNote: "25 g" },
      "polevka-cesnecka-cesnek": { label: "마늘 한 쪽 추가", portionNote: "1개" },
    },
  },
  "polevka-gulasova": {
    name: "굴라시 수프",
    description: "소고기, 파프리카.",
    portionNote: "약 350 ml (± 10 %)",
    ingredients: [{ name: "소고기" }, { name: "양파" }, { name: "파프리카" }, { name: "마늘" }],
    addons: {
      "polevka-gulasova-chleb-zdarma": { label: "빵", portionNote: "55 g" },
      "polevka-gulasova-maso": { label: "소고기 조각 추가", portionNote: "60 g" },
      "polevka-gulasova-chleb": { label: "바삭한 빵 추가", portionNote: "50 g" },
      "polevka-gulasova-kysela": { label: "피클 한 숟가락", portionNote: "40 g" },
      "polevka-gulasova-chilli": { label: "고추/칠리", portionNote: "15 g" },
    },
  },
  "polevka-dynova": {
    name: "단호박 크림 수프",
    description: "씨앗, 생크림.",
    portionNote: "약 300 ml (± 10 %)",
    ingredients: [{ name: "단호박" }, { name: "생크림" }, { name: "호박씨" }],
    addons: {
      "polevka-dynova-seminka": { label: "볶은 호박씨 추가", portionNote: "15 g" },
      "polevka-dynova-smetana": { label: "생크림 추가", portionNote: "30 ml" },
      "polevka-dynova-pečivo": { label: "그릴 빵", portionNote: "45 g" },
      "polevka-dynova-koren": { label: "따뜻한 향신료(시나몬, 육두구)", portionNote: "한 꼬집" },
    },
  },
  "predkrm-bruschetta": {
    name: "브루스케타",
    description: "토마토, 마늘, 올리브오일.",
    portionNote: "2개 · 약 160 g (± 10 %)",
    ingredients: [
      { name: "바게트" },
      { name: "토마토" },
      { name: "마늘" },
      { name: "올리브오일" },
      { name: "바질" },
    ],
    addons: {
      "predkrm-bruschetta-mozz": { label: "모짜렐라 추가", portionNote: "50 g" },
      "predkrm-bruschetta-olivy": { label: "올리브 추가", portionNote: "30 g" },
      "predkrm-bruschetta-kusy": { label: "브루스케타 한 조각 추가", portionNote: "1개" },
    },
  },
  "predkrm-tatarak": {
    name: "스테이크 타르타르",
    description: "토스트, 마늘. 취향에 맞게 섞어 드립니다.",
    portionNote: "약 190 g 고기 혼합 + 토스트 (± 10 %)",
    ingredients: [
      { name: "소고기" },
      { name: "노른자" },
      { name: "케이퍼" },
      { name: "머스타드" },
      { name: "토스트" },
      { name: "마늘" },
    ],
    addons: {
      "predkrm-tatarak-topinky": { label: "토스트 추가", portionNote: "3장" },
      "predkrm-tatarak-okurky": { label: "피클", portionNote: "40 g" },
      "predkrm-tatarak-zloutek": { label: "노른자 추가", portionNote: "1개" },
      "predkrm-tatarak-feferonka": { label: "고추(별도)", portionNote: "1개" },
    },
  },
  "predkrm-syr": {
    name: "치즈 보드",
    description: "치즈 모둠, 포도.",
    portionNote: "약 180 g 치즈 + 곁들임 (± 10 %)",
    ingredients: [{ name: "치즈 모둠" }, { name: "포도" }, { name: "견과" }],
    addons: {
      "predkrm-syr-hrozny": { label: "포도 추가", portionNote: "80 g" },
      "predkrm-syr-med": { label: "보드용 꿀", portionNote: "25 g" },
      "predkrm-syr-orechy": { label: "견과 추가", portionNote: "25 g" },
      "predkrm-syr-chutney": { label: "양파 챠트니", portionNote: "40 g" },
    },
  },
  "predkrm-olivy": {
    name: "마리네이드 올리브",
    description: "허브, 레몬.",
    portionNote: "약 120 g (± 10 %)",
    ingredients: [{ name: "올리브" }, { name: "허브" }, { name: "레몬" }],
    addons: {
      "predkrm-olivy-feta": { label: "페타 큐브", portionNote: "40 g" },
      "predkrm-olivy-chilli": { label: "고추", portionNote: "15 g" },
      "predkrm-olivy-pečivo": { label: "따뜻한 피타", portionNote: "1장" },
      "predkrm-olivy-citron": { label: "레몬즙 추가", portionNote: "10 ml" },
    },
  },
  "predkrm-krevety": {
    name: "마늘 새우",
    description: "칠리, 바게트.",
    portionNote: "약 200 g 새우 + 곁들임 (± 10 %)",
    ingredients: [{ name: "새우" }, { name: "마늘" }, { name: "칠리" }, { name: "바게트" }],
    addons: {
      "predkrm-krevety-porc": { label: "새우 2배", portionNote: "+120 g" },
      "predkrm-krevety-bageta": { label: "바게트 추가", portionNote: "1장" },
      "predkrm-krevety-citron": { label: "레몬·파슬리 추가", portionNote: "1/4개" },
      "predkrm-krevety-omacka": { label: "아이올리 딥", portionNote: "40 ml" },
    },
  },
  "hlavni-svickova": {
    name: "스비치코바(크림소스 소고기)",
    description: "빵 덤플링, 크랜베리.",
    portionNote: "약 480 g 전체(반찬 포함) (± 10 %)",
    ingredients: [{ name: "소고기" }, { name: "크림 소스" }, { name: "덤플링" }, { name: "크랜베리" }],
    addons: {
      "hlavni-svickova-extra-hovezi": { label: "소고기 추가", portionNote: "80 g" },
      "hlavni-svickova-knedlik": { label: "덤플링 추가", portionNote: "1개(~90 g)" },
      "hlavni-svickova-omacka": { label: "소스 추가", portionNote: "80 ml" },
      "hlavni-svickova-brusinky": { label: "크랜베리/칩 추가", portionNote: "40 g" },
      "hlavni-svickova-kysela": { label: "피클 오이", portionNote: "1개" },
    },
  },
  "hlavni-gulas": {
    name: "소고기 굴라시",
    description: "양파, 파프리카, 빵.",
    portionNote: "약 450 g (± 10 %)",
    ingredients: [{ name: "소고기" }, { name: "양파" }, { name: "파프리카" }, { name: "빵" }],
    addons: {
      "hlavni-gulas-maso": { label: "고기 추가", portionNote: "60 g" },
      "hlavni-gulas-kyselo": { label: "사워크라우트/양배추(별도)", portionNote: "120 g" },
      "hlavni-gulas-chleb": { label: "빵 추가", portionNote: "60 g" },
      "hlavni-gulas-cibule": { label: "볶은 양파 토핑", portionNote: "40 g" },
    },
  },
  "hlavni-salat": {
    name: "시저 샐러드",
    description: "닭고기, 파마산, 드레싱.",
    portionNote: "약 320 g (± 10 %)",
    ingredients: [
      { name: "로메인" },
      { name: "닭고기" },
      { name: "파마산" },
      { name: "크루통" },
      { name: "드레싱" },
    ],
    addons: {
      "hlavni-salat-kure": { label: "그릴 닭고기 추가", portionNote: "80 g" },
      "hlavni-salat-ančovičky": { label: "멸치", portionNote: "15 g" },
      "hlavni-salat-parmazan": { label: "파마산 슬라이스 추가", portionNote: "15 g" },
      "hlavni-salat-krutony": { label: "크루통 추가", portionNote: "30 g" },
    },
  },
  "hlavni-rizek": {
    name: "치킨 슈니첼",
    description: "곁들임 선택, 레몬.",
    portionNote: "약 420 g(반찬 포함) (± 10 %)",
    ingredients: [{ name: "닭고기" }, { name: "빵가루" }, { name: "레몬" }],
    sideChoice: {
      sectionLabel: "곁들임",
      options: {
        "rizek-side-brambory": { label: "감자" },
        "rizek-side-kase": { label: "매시드 포테이토" },
        "rizek-side-hranolky": { label: "감자튀김" },
        "rizek-side-bataty": { label: "고구마튀김" },
      },
    },
    addons: {
      "hlavni-rizek-tatarka": { label: "타르타르 소스", portionNote: "40 ml" },
      "hlavni-rizek-kedlubny": { label: "콜라비 샐러드", portionNote: "100 g" },
      "hlavni-rizek-citron": { label: "레몬 조각 추가", portionNote: "1/2개" },
    },
  },
  "hlavni-supreme": {
    name: "치킨 슈프림",
    description:
      "그릴 닭가슴살, 크림 소스, 파마 햄, 파마산, 버섯을 곁들인 그릴 채소. 곁들임 하나 선택.",
    portionNote: "약 430 g(반찬 포함) (± 10 %)",
    ingredients: [
      { name: "닭가슴살" },
      { name: "크림 소스" },
      { name: "파마 햄" },
      { name: "파마산" },
      { name: "그릴 채소" },
      { name: "버섯" },
    ],
    sideChoice: {
      sectionLabel: "곁들임",
      options: {
        "supreme-side-brambory": { label: "감자" },
        "supreme-side-kase": { label: "매시드 포테이토" },
        "supreme-side-hranolky": { label: "감자튀김" },
        "supreme-side-bataty": { label: "고구마튀김" },
      },
    },
    addons: {
      "hlavni-supreme-prso": { label: "닭가슴살 추가", portionNote: "100 g" },
      "hlavni-supreme-omacka": { label: "소스 추가", portionNote: "60 ml" },
      "hlavni-supreme-sunka": { label: "햄 추가", portionNote: "25 g" },
      "hlavni-supreme-syr": { label: "파마산 슬라이스 추가", portionNote: "12 g" },
      "hlavni-supreme-zampiony": { label: "버섯 추가", portionNote: "40 g" },
      "hlavni-supreme-zelenina": { label: "그릴 채소 추가", portionNote: "100 g" },
      "hlavni-supreme-tatarka": { label: "타르타르 소스", portionNote: "40 ml" },
    },
  },
  "hlavni-burger": {
    name: "소고기 버거",
    description: "번, 치즈, 채소, 드레싱. 감자튀김·고구마튀김·콜슬로는 옵션에서 추가.",
    portionNote: "약 320 g 버거 (± 10 %)",
    ingredients: [{ name: "소고기" }, { name: "번" }, { name: "치즈" }, { name: "채소" }],
    addonsSectionLabel: "옵션",
    addons: {
      "burger-side-hranolky": { label: "감자튀김", portionNote: "150 g" },
      "burger-side-bataty": { label: "고구마튀김", portionNote: "150 g" },
      "burger-side-coleslaw": { label: "콜슬로", portionNote: "120 g" },
      "burger-extra-cheese": { label: "치즈 슬라이스 추가", portionNote: "25 g" },
      "burger-extra-meat": { label: "소고기 패티 추가", portionNote: "90 g" },
      "burger-extra-onion": { label: "신선 양파 추가", portionNote: "20 g" },
      "burger-extra-bacon": { label: "바삭한 베이컨", portionNote: "30 g" },
      "burger-extra-jalapeno": { label: "할라피뇨", portionNote: "25 g" },
      "burger-extra-bbq": { label: "BBQ 소스 추가", portionNote: "30 ml" },
    },
  },
  "hlavni-testoviny": {
    name: "까보나라 파스타",
    description: "판체타, 파마산.",
    portionNote: "약 400 g (± 10 %)",
    ingredients: [
      { name: "파스타" },
      { name: "판체타" },
      { name: "달걀" },
      { name: "파마산" },
      { name: "후추" },
    ],
    addons: {
      "hlavni-testoviny-parmazan": { label: "파마산 추가", portionNote: "15 g" },
      "hlavni-testoviny-pancetta": { label: "판체타 추가", portionNote: "35 g" },
      "hlavni-testoviny-chilli": { label: "칠리 추가", portionNote: "5 g" },
      "hlavni-testoviny-truffle": { label: "트러플 오일 몇 방울", portionNote: "5 ml" },
    },
  },
  "hlavni-losos": {
    name: "그릴 연어",
    description: "그릴 채소. 감자·매시·감자튀김·고구마튀김은 옵션에서 추가.",
    portionNote: "약 280 g 연어와 채소 (± 10 %)",
    ingredients: [{ name: "연어" }, { name: "채소" }],
    addonsSectionLabel: "옵션",
    addons: {
      "hlavni-losos-side-brambory": { label: "감자", portionNote: "150 g" },
      "hlavni-losos-side-stouchane": { label: "으깬 감자", portionNote: "200 g" },
      "hlavni-losos-side-kase": { label: "매시드 포테이토", portionNote: "200 g" },
      "hlavni-losos-side-hranolky": { label: "감자튀김", portionNote: "150 g" },
      "hlavni-losos-side-bataty": { label: "고구마튀김", portionNote: "150 g" },
      "hlavni-losos-koprova": { label: "딜 딥/소스", portionNote: "50 ml" },
      "hlavni-losos-zelenina": { label: "그릴 채소 추가", portionNote: "120 g" },
      "hlavni-losos-citron": { label: "레몬과 케이퍼", portionNote: "20 g" },
    },
  },
  "hlavni-vege": {
    name: "베지 보울",
    description: "퀴노아, 후무스, 채소.",
    portionNote: "약 360 g (± 10 %)",
    ingredients: [{ name: "퀴노아" }, { name: "후무스" }, { name: "채소" }, { name: "씨앗" }],
    addons: {
      "hlavni-vege-hummus": { label: "후무스 추가", portionNote: "60 g" },
      "hlavni-vege-avokado": { label: "아보카도 슬라이스", portionNote: "1/2개" },
      "hlavni-vege-tahini": { label: "타히니 드레싱", portionNote: "40 ml" },
      "hlavni-vege-seminka": { label: "볶은 씨앗 믹스", portionNote: "15 g" },
    },
  },
  "dessert-cheesecake": {
    name: "치즈케이크",
    description: "베리.",
    portionNote: "약 140 g (± 10 %)",
    ingredients: [{ name: "크림치즈" }, { name: "비스킷" }, { name: "베리" }],
    addons: {
      "dessert-cheesecake-omacka": { label: "베리 소스", portionNote: "50 ml" },
      "dessert-cheesecake-slehacka": { label: "휘핑크림", portionNote: "40 ml" },
      "dessert-cheesecake-orechy": { label: "캐러멜 견과", portionNote: "25 g" },
      "dessert-cheesecake-kousek": { label: "큰 한 조각(추가 1조각)", portionNote: "+120 g" },
    },
  },
  "dessert-tiramisu": {
    name: "티라미수",
    description: "커피, 마스카포네.",
    portionNote: "약 130 g (± 10 %)",
    ingredients: [{ name: "마스카포네" }, { name: "커피" }, { name: "사보라디 쿠키" }, { name: "코코아" }],
    addons: {
      "dessert-tiramisu-kakao": { label: "코코아 추가", portionNote: "5 g" },
      "dessert-tiramisu-espresso": { label: "끼얹는 에스프레소", portionNote: "30 ml" },
      "dessert-tiramisu-amaretto": { label: "아마레또 시럽(무알콜)", portionNote: "20 ml" },
      "dessert-tiramisu-slehacka": { label: "별도 휘핑크림", portionNote: "40 ml" },
    },
  },
  "dessert-pala": {
    name: "크레페",
    description: "취향대로 골라 주문하세요",
    portionNote: "기본 크레페 2장 (± 10 %)",
    ingredients: [{ name: "크레페" }, { name: "누텔라" }, { name: "과일" }],
    multiPickGroups: [
      {
        id: "pala-grp-sladke",
        sectionLabel: "단맛 토핑",
        options: {
          "pala-sladke-none": { label: "단맛 토핑 없음" },
          "pala-sladke-banan": { label: "바나나" },
          "pala-sladke-boruvky": { label: "블루베리" },
          "pala-sladke-jahody": { label: "딸기" },
          "pala-sladke-lesni": { label: "산딸기·야생베리" },
          "pala-sladke-ciniminis": { label: "부순 시니 미니스" },
          "pala-sladke-kinder-bueno": { label: "킨더 부에노" },
          "pala-sladke-kinder-coko": { label: "킨더 초콜릿" },
          "pala-sladke-kinder-maxi": { label: "킨더 맥시 킹" },
          "pala-sladke-kokos": { label: "코코넛" },
          "pala-sladke-lotus": { label: "로터스 부숨" },
          "pala-sladke-oreo": { label: "오레오" },
          "pala-sladke-orisky": { label: "견과" },
          "pala-sladke-maliny": { label: "라즈베리" },
        },
      },
      {
        id: "pala-grp-slane",
        sectionLabel: "짭짤한 토핑",
        options: {
          "pala-slane-none": { label: "짭짤한 토핑 없음" },
          "pala-slane-spenat": { label: "신선 시금치" },
          "pala-slane-cheddar": { label: "체다 소스" },
          "pala-slane-sunka": { label: "햄" },
          "pala-slane-kure": { label: "닭고기" },
          "pala-slane-syr": { label: "강판 치즈" },
          "pala-slane-kukurice": { label: "옥수수" },
          "pala-slane-slanina": { label: "베이컨" },
          "pala-slane-zampiony": { label: "버섯" },
          "pala-slane-salam": { label: "살라미" },
        },
      },
      {
        id: "pala-grp-sladka-pol",
        sectionLabel: "단 소스",
        options: {
          "pala-spol-none": { label: "소스 없음" },
          "pala-spol-coko": { label: "초콜릿 소스" },
          "pala-spol-jahoda": { label: "딸기 소스" },
          "pala-spol-javor": { label: "메이플 시럽" },
          "pala-spol-karamel": { label: "캐러멜 토핑" },
          "pala-spol-vanilka": { label: "바닐라 소스" },
          "pala-spol-bila-coko": { label: "화이트 초콜릿" },
          "pala-spol-malina": { label: "라즈베리 소스" },
          "pala-spol-kondenz": { label: "연유" },
        },
      },
    ],
    savoryGlazeChoice: {
      sectionLabel: "짠 소스",
      options: {
        "pala-slpol-bez": { label: "소스 없음" },
        "pala-slpol-cheddar": { label: "체다 소스" },
        "pala-slpol-smetana": { label: "사워크림" },
        "pala-slpol-kecup": { label: "케첩" },
        "pala-slpol-majo": { label: "마요네즈" },
      },
    },
  },
  "dessert-zmrz": {
    name: "아이스크림 선데",
    description: "초콜릿, 휘핑크림.",
    portionNote: "약 200 g (± 10 %)",
    ingredients: [{ name: "아이스크림" }, { name: "초콜릿" }, { name: "휘핑크림" }],
    addons: {
      "dessert-zmrz-kopecek": { label: "아이스크림 스쿱 추가", portionNote: "50 g" },
      "dessert-zmrz-poleva": { label: "초콜릿 소스 추가", portionNote: "30 ml" },
      "dessert-zmrz-orechy": { label: "견과/바삭 토핑", portionNote: "20 g" },
      "dessert-zmrz-ovoce": { label: "신선 과일", portionNote: "60 g" },
    },
  },
  "dessert-kolac": {
    name: "사과 파이",
    description: "시나몬, 바닐라 소스.",
    portionNote: "약 150 g (± 10 %)",
    ingredients: [{ name: "사과" }, { name: "시나몬" }, { name: "페이스트리" }, { name: "바닐라 소스" }],
    addons: {
      "dessert-kolac-zmrzlina": { label: "바닐라 아이스크림 스쿱", portionNote: "50 g" },
      "dessert-kolac-omacka": { label: "바닐라 소스 추가", portionNote: "50 ml" },
      "dessert-kolac-slehacka": { label: "휘핑크림", portionNote: "40 ml" },
      "dessert-kolac-skorice": { label: "윗면 시나몬 슈가", portionNote: "2 g" },
    },
  },
  "napoj-voda": {
    name: "물",
    description: "스틸 / 탄산.",
    portionNote: "0.33 l (± 5 ml); 큰 병은 추가 요금",
    ingredients: [{ name: "물" }],
    addons: {
      "napoj-voda-citron": { label: "레몬/라임", portionNote: "2장" },
      "napoj-voda-velka": { label: "큰 병 (0.75 l)", portionNote: "750 ml" },
      "napoj-voda-perliva": { label: "탄산으로 변경", portionNote: "동일 용량" },
    },
  },
  "napoj-kola": {
    name: "콜라",
    description: "0.33 l.",
    portionNote: "기본 0.33 l (0.5 l 추가 시, ± 5 ml)",
    ingredients: [{ name: "콜라" }],
    addons: {
      "cola-05": { label: "0.5 L", portionNote: "500 ml" },
      "napoj-kola-led": { label: "얼음", portionNote: "약 80 g" },
      "napoj-kola-citron": { label: "레몬 슬라이스", portionNote: "1장" },
    },
  },
  "napoj-pivo": {
    name: "맥주",
    description: "0.3 l.",
    portionNote: "0.3 l (± 10 ml)",
    ingredients: [{ name: "맥주" }],
    addons: {
      "napoj-pivo-velke": { label: "큰 맥주", portionNote: "0.5 l" },
    },
  },
  "napoj-kava": {
    name: "에스프레소",
    description: "싱글 샷.",
    portionNote: "약 40 ml(싱글); 더블은 추가 요금",
    ingredients: [{ name: "커피" }],
    addons: {
      "double-shot": { label: "더블 샷", portionNote: "+40 ml" },
      "napoj-kava-americano": { label: "아메리카노", portionNote: "뜨거운 물 약 120 ml" },
      "napoj-kava-mleko": { label: "우유", portionNote: "60 ml" },
      "napoj-kava-sojove": { label: "두유", portionNote: "60 ml" },
      "napoj-kava-cokolada": { label: "초콜릿 에스프레소(모카)", portionNote: "25 ml" },
      "napoj-kava-led": { label: "얼음 추가", portionNote: "약 60 g" },
    },
  },
  "napoj-caj": {
    name: "차",
    description: "선택 가능.",
    portionNote: "약 0.25–0.3 l 컵 (± 10 %)",
    ingredients: [{ name: "차" }],
    sideChoice: {
      sectionLabel: "차 맛",
      summaryLabel: "맛",
      options: {
        "napoj-caj-cerny": { label: "홍차" },
        "napoj-caj-matovy": { label: "페퍼민트" },
        "napoj-caj-ovocny": { label: "과일차" },
        "napoj-caj-mango": { label: "망고" },
        "napoj-caj-zeleny": { label: "녹차" },
        "napoj-caj-bylinkovy": { label: "허브차" },
        "napoj-caj-rooibos": { label: "루이보스" },
      },
    },
    addonsSectionLabel: "추가",
    addons: {
      milk: { label: "우유", portionNote: "50 ml" },
      "napoj-caj-med": { label: "꿀", portionNote: "15 g" },
      "napoj-caj-citron": { label: "레몬", portionNote: "1장" },
    },
  },
  "napoj-limo": {
    name: "수제 레모네이드",
    description: "0.4 l, 맛 선택.",
    portionNote: "0.4 l (큰 사이즈 추가 시 0.7 l, ± 5 ml)",
    ingredients: [{ name: "감귤" }, { name: "민트" }, { name: "소다" }],
    sideChoice: {
      sectionLabel: "레모네이드 맛",
      summaryLabel: "맛",
      options: {
        "napoj-limo-jahody": { label: "딸기" },
        "napoj-limo-mango": { label: "망고" },
        "napoj-limo-pomeranc": { label: "오렌지" },
        "napoj-limo-citron": { label: "레몬" },
      },
    },
    addonsSectionLabel: "추가 옵션",
    addons: {
      "napoj-limo-mata": { label: "민트 추가", portionNote: "5 g" },
      "napoj-limo-velka": { label: "큰 사이즈", portionNote: "0.7 l" },
    },
  },
  "napoj-vino": {
    name: "와인(글라스)",
    description: "0.2 l.",
    portionNote: "0.2 l (추가 시 0.3 l, ± 5 ml)",
    ingredients: [{ name: "와인" }],
    addons: {
      "napoj-vino-deci": { label: "0.1 l 추가(총 0.3 l)", portionNote: "100 ml" },
      "napoj-vino-soda": { label: "스프리처(소다)", portionNote: "80 ml" },
      "napoj-vino-led": { label: "얼음 추가", portionNote: "약 60 g" },
    },
  },
};
