/**
 * Fiktivní provozovna jako v Dotyce: jídla s recepturami, sklad v kg, pool příloh, obaly.
 * Nepíše se do ostré pokladny — jen na ověření filtru kiosku.
 */

export const SIM_CAT = {
  hlavni: 1,
  polevky: 2,
  naboje: 3,
  dezerty: 4,
  ingredience: 5,
  sklad: 6,
  prilohy: 7,
  prilohyBurger: 8,
  obaly: 9,
  drogerie: 10,
} as const;

export const SIM_ID = {
  svickova: 101,
  rizek: 102,
  burger: 103,
  gulas: 104,
  pizza: 105,
  smazenySyr: 106,
  kureciSteak: 107,
  tatarak: 108,
  fishChips: 109,
  caesar: 110,
  polevkaDne: 111,
  cesnecka: 112,
  pivo: 113,
  kofola: 114,
  espresso: 115,
  vino: 116,
  limonada: 117,
  cheesecake: 118,
  tiramisu: 119,
  zmrzlina: 120,
  hovezi: 201,
  veprova: 202,
  kureci: 203,
  sul: 204,
  pepr: 205,
  mouka: 206,
  maslo: 207,
  cibule: 208,
  cesnek: 209,
  smetana: 210,
  rajce: 211,
  ledovySalat: 212,
  cheddar: 213,
  houska: 214,
  brambory: 215,
  olej: 301,
  cukr: 302,
  ryze: 303,
  hranolky: 401,
  stouchane: 402,
  opekane: 403,
  domaciSalat: 404,
  bbq: 405,
  cesnekovyDip: 406,
  extraSyr: 407,
  slanina: 408,
  ubrousky: 501,
  dezinfekce: 502,
  volna: 601,
  hadrik: 602,
} as const;

function cat(
  id: number,
  name: string,
  extra: Record<string, unknown> = {},
): Record<string, unknown> {
  return { id, name, display: true, deleted: false, sortOrder: id, ...extra };
}

function product(
  id: number,
  name: string,
  categoryId: number,
  extra: Record<string, unknown> = {},
): Record<string, unknown> {
  return {
    id,
    name,
    _categoryId: categoryId,
    display: true,
    deleted: false,
    unit: "Piece",
    ...extra,
  };
}

export const simulationCategories: Record<string, unknown>[] = [
  cat(SIM_CAT.hlavni, "Hlavní jídla"),
  cat(SIM_CAT.polevky, "Polévky"),
  cat(SIM_CAT.naboje, "Nápoje"),
  cat(SIM_CAT.dezerty, "Dezerty"),
  cat(SIM_CAT.ingredience, "Ingredience"),
  cat(SIM_CAT.sklad, "Sklad suroviny"),
  cat(SIM_CAT.prilohy, "Přílohy"),
  cat(SIM_CAT.prilohyBurger, "Přílohy burger"),
  cat(SIM_CAT.obaly, "Obaly"),
  cat(SIM_CAT.drogerie, "Drogerie"),
];

export const simulationProducts: Record<string, unknown>[] = [
  product(SIM_ID.svickova, "Svíčková", SIM_CAT.hlavni),
  product(SIM_ID.rizek, "Řízek", SIM_CAT.hlavni),
  product(SIM_ID.burger, "Burger Classic", SIM_CAT.hlavni, {
    customizations: [{ id: 1, _categoryId: SIM_CAT.prilohyBurger }],
  }),
  product(SIM_ID.gulas, "Guláš", SIM_CAT.hlavni),
  product(SIM_ID.pizza, "Pizza Margherita", SIM_CAT.hlavni),
  product(SIM_ID.smazenySyr, "Smažený sýr", SIM_CAT.hlavni),
  product(SIM_ID.kureciSteak, "Kuřecí steak", SIM_CAT.hlavni),
  product(SIM_ID.tatarak, "Tatarský biftek", SIM_CAT.hlavni),
  product(SIM_ID.fishChips, "Fish & chips", SIM_CAT.hlavni),
  product(SIM_ID.caesar, "Caesar salát", SIM_CAT.hlavni),
  product(SIM_ID.polevkaDne, "Polévka dne", SIM_CAT.polevky),
  product(SIM_ID.cesnecka, "Česnečka", SIM_CAT.polevky),
  product(SIM_ID.pivo, "Pivo 0,5 l", SIM_CAT.naboje),
  product(SIM_ID.kofola, "Kofola", SIM_CAT.naboje),
  product(SIM_ID.espresso, "Espresso", SIM_CAT.naboje),
  product(SIM_ID.vino, "Víno bílé", SIM_CAT.naboje),
  product(SIM_ID.limonada, "Domácí limonáda", SIM_CAT.naboje),
  product(SIM_ID.cheesecake, "Cheesecake", SIM_CAT.dezerty),
  product(SIM_ID.tiramisu, "Tiramisu", SIM_CAT.dezerty),
  product(SIM_ID.zmrzlina, "Zmrzlina", SIM_CAT.dezerty),

  product(SIM_ID.hovezi, "Hovězí zadní", SIM_CAT.ingredience),
  product(SIM_ID.veprova, "Vepřová kotleta", SIM_CAT.ingredience),
  product(SIM_ID.kureci, "Kuřecí prsa", SIM_CAT.ingredience),
  product(SIM_ID.sul, "Sůl", SIM_CAT.ingredience),
  product(SIM_ID.pepr, "Pepř", SIM_CAT.ingredience),
  product(SIM_ID.mouka, "Mouka", SIM_CAT.ingredience),
  product(SIM_ID.maslo, "Máslo", SIM_CAT.ingredience),
  product(SIM_ID.cibule, "Cibule", SIM_CAT.ingredience),
  product(SIM_ID.cesnek, "Česnek", SIM_CAT.ingredience),
  product(SIM_ID.smetana, "Smetana", SIM_CAT.ingredience),
  product(SIM_ID.rajce, "Rajče", SIM_CAT.ingredience),
  product(SIM_ID.ledovySalat, "Ledový salát", SIM_CAT.ingredience),
  product(SIM_ID.cheddar, "Cheddar", SIM_CAT.ingredience),
  product(SIM_ID.houska, "Houska burger", SIM_CAT.ingredience),
  product(SIM_ID.brambory, "Brambory", SIM_CAT.ingredience),

  product(SIM_ID.olej, "Olej", SIM_CAT.sklad, { unit: "Kilogram" }),
  product(SIM_ID.cukr, "Cukr", SIM_CAT.sklad, { unit: "Kilogram" }),
  product(SIM_ID.ryze, "Rýže sypká", SIM_CAT.sklad, { unit: "Kilogram" }),

  product(SIM_ID.hranolky, "Hranolky", SIM_CAT.prilohy),
  product(SIM_ID.stouchane, "Šťouchané brambory", SIM_CAT.prilohy),
  product(SIM_ID.opekane, "Opékané brambory", SIM_CAT.prilohy),
  product(SIM_ID.domaciSalat, "Domácí salát", SIM_CAT.prilohy),
  product(SIM_ID.bbq, "BBQ dip", SIM_CAT.prilohyBurger),
  product(SIM_ID.cesnekovyDip, "Česnekový dip", SIM_CAT.prilohyBurger),
  product(SIM_ID.extraSyr, "Extra sýr", SIM_CAT.prilohyBurger),
  product(SIM_ID.slanina, "Slanina extra", SIM_CAT.prilohyBurger),

  product(SIM_ID.ubrousky, "Ubrousky", SIM_CAT.obaly),
  product(SIM_ID.dezinfekce, "Dezinfekce", SIM_CAT.drogerie),
  product(SIM_ID.volna, "Volná položka", SIM_CAT.hlavni, { requiresPriceEntry: true }),
  product(SIM_ID.hadrik, "Hadřík", SIM_CAT.hlavni, { tags: ["sklad"] }),
];

/** Dítě = surovina / polotovar, rodič = jídlo (nebo hranolky jako polotovar). */
export const simulationIngredientRows: Record<string, unknown>[] = [
  { _parentProductId: SIM_ID.svickova, _productId: SIM_ID.hovezi },
  { _parentProductId: SIM_ID.svickova, _productId: SIM_ID.smetana },
  { _parentProductId: SIM_ID.svickova, _productId: SIM_ID.cibule },
  { _parentProductId: SIM_ID.svickova, _productId: SIM_ID.sul },
  { _parentProductId: SIM_ID.svickova, _productId: SIM_ID.mouka },
  { _parentProductId: SIM_ID.rizek, _productId: SIM_ID.veprova },
  { _parentProductId: SIM_ID.rizek, _productId: SIM_ID.mouka },
  { _parentProductId: SIM_ID.rizek, _productId: SIM_ID.sul },
  { _parentProductId: SIM_ID.burger, _productId: SIM_ID.houska },
  { _parentProductId: SIM_ID.burger, _productId: SIM_ID.kureci },
  { _parentProductId: SIM_ID.burger, _productId: SIM_ID.cheddar },
  { _parentProductId: SIM_ID.burger, _productId: SIM_ID.ledovySalat },
  { _parentProductId: SIM_ID.burger, _productId: SIM_ID.rajce },
  { _parentProductId: SIM_ID.gulas, _productId: SIM_ID.hovezi },
  { _parentProductId: SIM_ID.gulas, _productId: SIM_ID.cibule },
  { _parentProductId: SIM_ID.gulas, _productId: SIM_ID.cesnek },
  { _parentProductId: SIM_ID.gulas, _productId: SIM_ID.pepr },
  { _parentProductId: SIM_ID.pizza, _productId: SIM_ID.rajce },
  { _parentProductId: SIM_ID.pizza, _productId: SIM_ID.cheddar },
  { _parentProductId: SIM_ID.pizza, _productId: SIM_ID.mouka },
  { _parentProductId: SIM_ID.smazenySyr, _productId: SIM_ID.cheddar },
  { _parentProductId: SIM_ID.smazenySyr, _productId: SIM_ID.mouka },
  { _parentProductId: SIM_ID.kureciSteak, _productId: SIM_ID.kureci },
  { _parentProductId: SIM_ID.kureciSteak, _productId: SIM_ID.maslo },
  { _parentProductId: SIM_ID.kureciSteak, _productId: SIM_ID.cesnek },
  { _parentProductId: SIM_ID.tatarak, _productId: SIM_ID.hovezi },
  { _parentProductId: SIM_ID.tatarak, _productId: SIM_ID.cibule },
  { _parentProductId: SIM_ID.tatarak, _productId: SIM_ID.cesnek },
  { _parentProductId: SIM_ID.fishChips, _productId: SIM_ID.hranolky },
  { _parentProductId: SIM_ID.fishChips, _productId: SIM_ID.mouka },
  { _parentProductId: SIM_ID.caesar, _productId: SIM_ID.ledovySalat },
  { _parentProductId: SIM_ID.caesar, _productId: SIM_ID.cesnek },
  { _parentProductId: SIM_ID.polevkaDne, _productId: SIM_ID.cibule },
  { _parentProductId: SIM_ID.polevkaDne, _productId: SIM_ID.maslo },
  { _parentProductId: SIM_ID.polevkaDne, _productId: SIM_ID.sul },
  { _parentProductId: SIM_ID.cesnecka, _productId: SIM_ID.cesnek },
  { _parentProductId: SIM_ID.cesnecka, _productId: SIM_ID.sul },
  { _parentProductId: SIM_ID.cesnecka, _productId: SIM_ID.maslo },
  { _parentProductId: SIM_ID.hranolky, _productId: SIM_ID.brambory },
  { _parentProductId: SIM_ID.hranolky, _productId: SIM_ID.olej },
];

export const SIMULATION_EXPECTED_SHOWN = [
  "Svíčková",
  "Řízek",
  "Burger Classic",
  "Guláš",
  "Pizza Margherita",
  "Smažený sýr",
  "Kuřecí steak",
  "Tatarský biftek",
  "Fish & chips",
  "Caesar salát",
  "Polévka dne",
  "Česnečka",
  "Pivo 0,5 l",
  "Kofola",
  "Espresso",
  "Víno bílé",
  "Domácí limonáda",
  "Cheesecake",
  "Tiramisu",
  "Zmrzlina",
] as const;
